# Site settings
title: SPY vs CAT5
description: "Club de hacking de l'université Laval"
baseurl: "" # the subpath of your site
url: "https://spyvscat5.github.io"

# User settings
username: SPY vs CAT5
user_title: SPY vs CAT5
email: clubhacking@fsg.ulaval.ca
github_username:  SpyVsCat5
youtube_username:  UCqHR0icKT20KwFDjaZuFt7w

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Accueil
    url: /
  - title: À propos
    url: /about
  - title: Événements
    url: /events
  - title: Laboratoire
    url: /laboratory
  - title: Ressources
    url: /resources

# projects in header index
projects:
  - name: Workshops / Présentations
    url: https://github.com/SpyVsCat5/Workshops

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
